"""Initial

Revision ID: e5a164d8a4c3
Revises: 
Create Date: 2023-09-06 20:01:07.218535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e5a164d8a4c3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("file", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("followers", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("following", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=True)
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=True)
    op.create_table(
        "tokens",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("api_key", sa.String(length=200), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tokens_api_key"), "tokens", ["api_key"], unique=True)
    op.create_index(op.f("ix_tokens_id"), "tokens", ["id"], unique=True)
    op.create_table(
        "tweets",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("content", sa.String(length=10000), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tweets_id"), "tweets", ["id"], unique=True)
    op.create_table(
        "likes",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("tweet_id", sa.BIGINT(), nullable=False),
        sa.ForeignKeyConstraint(["tweet_id"], ["tweets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "user_id", "tweet_id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("user_id", "tweet_id", name="_user_tweet_uc"),
    )
    op.create_table(
        "tweet_media",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("tweet_id", sa.BIGINT(), nullable=False),
        sa.Column("media_id", sa.BIGINT(), nullable=False),
        sa.ForeignKeyConstraint(["media_id"], ["media.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tweet_id"], ["tweets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "tweet_id", "media_id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("media_id", "tweet_id", name="_tweet_media_uc"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tweet_media")
    op.drop_table("likes")
    op.drop_index(op.f("ix_tweets_id"), table_name="tweets")
    op.drop_table("tweets")
    op.drop_index(op.f("ix_tokens_id"), table_name="tokens")
    op.drop_index(op.f("ix_tokens_api_key"), table_name="tokens")
    op.drop_table("tokens")
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("media")
    # ### end Alembic commands ###
